/*
This code is auto-generated by k8s.io/code-generator
*/package v1alpha1

import (
	v1alpha1 "github.com/radu-matei/learning-operator/pkg/apis/example/v1alpha1"
	scheme "github.com/radu-matei/learning-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SimpleExamplesGetter has a method to return a SimpleExampleInterface.
// A group's client should implement this interface.
type SimpleExamplesGetter interface {
	SimpleExamples(namespace string) SimpleExampleInterface
}

// SimpleExampleInterface has methods to work with SimpleExample resources.
type SimpleExampleInterface interface {
	Create(*v1alpha1.SimpleExample) (*v1alpha1.SimpleExample, error)
	Update(*v1alpha1.SimpleExample) (*v1alpha1.SimpleExample, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SimpleExample, error)
	List(opts v1.ListOptions) (*v1alpha1.SimpleExampleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleExample, err error)
	SimpleExampleExpansion
}

// simpleExamples implements SimpleExampleInterface
type simpleExamples struct {
	client rest.Interface
	ns     string
}

// newSimpleExamples returns a SimpleExamples
func newSimpleExamples(c *ExampleV1alpha1Client, namespace string) *simpleExamples {
	return &simpleExamples{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the simpleExample, and returns the corresponding simpleExample object, and an error if there is any.
func (c *simpleExamples) Get(name string, options v1.GetOptions) (result *v1alpha1.SimpleExample, err error) {
	result = &v1alpha1.SimpleExample{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpleexamples").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SimpleExamples that match those selectors.
func (c *simpleExamples) List(opts v1.ListOptions) (result *v1alpha1.SimpleExampleList, err error) {
	result = &v1alpha1.SimpleExampleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("simpleexamples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested simpleExamples.
func (c *simpleExamples) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("simpleexamples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a simpleExample and creates it.  Returns the server's representation of the simpleExample, and an error, if there is any.
func (c *simpleExamples) Create(simpleExample *v1alpha1.SimpleExample) (result *v1alpha1.SimpleExample, err error) {
	result = &v1alpha1.SimpleExample{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("simpleexamples").
		Body(simpleExample).
		Do().
		Into(result)
	return
}

// Update takes the representation of a simpleExample and updates it. Returns the server's representation of the simpleExample, and an error, if there is any.
func (c *simpleExamples) Update(simpleExample *v1alpha1.SimpleExample) (result *v1alpha1.SimpleExample, err error) {
	result = &v1alpha1.SimpleExample{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("simpleexamples").
		Name(simpleExample.Name).
		Body(simpleExample).
		Do().
		Into(result)
	return
}

// Delete takes name of the simpleExample and deletes it. Returns an error if one occurs.
func (c *simpleExamples) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpleexamples").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *simpleExamples) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("simpleexamples").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched simpleExample.
func (c *simpleExamples) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SimpleExample, err error) {
	result = &v1alpha1.SimpleExample{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("simpleexamples").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
