/*
This code is auto-generated by k8s.io/code-generator
*/
// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/radu-matei/learning-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SimpleExamples returns a SimpleExampleInformer.
	SimpleExamples() SimpleExampleInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SimpleExamples returns a SimpleExampleInformer.
func (v *version) SimpleExamples() SimpleExampleInformer {
	return &simpleExampleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
