/*
This code is auto-generated by k8s.io/code-generator
*/
// This file was automatically generated by informer-gen

package v1alpha1

import (
	example_v1alpha1 "github.com/radu-matei/learning-operator/pkg/apis/example/v1alpha1"
	versioned "github.com/radu-matei/learning-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/radu-matei/learning-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/radu-matei/learning-operator/pkg/client/listers/example/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// SimpleExampleInformer provides access to a shared informer and lister for
// SimpleExamples.
type SimpleExampleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SimpleExampleLister
}

type simpleExampleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSimpleExampleInformer constructs a new informer for SimpleExample type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSimpleExampleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSimpleExampleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSimpleExampleInformer constructs a new informer for SimpleExample type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSimpleExampleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().SimpleExamples(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().SimpleExamples(namespace).Watch(options)
			},
		},
		&example_v1alpha1.SimpleExample{},
		resyncPeriod,
		indexers,
	)
}

func (f *simpleExampleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSimpleExampleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *simpleExampleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&example_v1alpha1.SimpleExample{}, f.defaultInformer)
}

func (f *simpleExampleInformer) Lister() v1alpha1.SimpleExampleLister {
	return v1alpha1.NewSimpleExampleLister(f.Informer().GetIndexer())
}
