/*
This code is auto-generated by k8s.io/code-generator
*/
// This file was automatically generated by lister-gen

package v1alpha1

// SimpleExampleListerExpansion allows custom methods to be added to
// SimpleExampleLister.
type SimpleExampleListerExpansion interface{}

// SimpleExampleNamespaceListerExpansion allows custom methods to be added to
// SimpleExampleNamespaceLister.
type SimpleExampleNamespaceListerExpansion interface{}
