/*
This code is auto-generated by k8s.io/code-generator
*/
// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/radu-matei/learning-operator/pkg/apis/example/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SimpleExampleLister helps list SimpleExamples.
type SimpleExampleLister interface {
	// List lists all SimpleExamples in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.SimpleExample, err error)
	// SimpleExamples returns an object that can list and get SimpleExamples.
	SimpleExamples(namespace string) SimpleExampleNamespaceLister
	SimpleExampleListerExpansion
}

// simpleExampleLister implements the SimpleExampleLister interface.
type simpleExampleLister struct {
	indexer cache.Indexer
}

// NewSimpleExampleLister returns a new SimpleExampleLister.
func NewSimpleExampleLister(indexer cache.Indexer) SimpleExampleLister {
	return &simpleExampleLister{indexer: indexer}
}

// List lists all SimpleExamples in the indexer.
func (s *simpleExampleLister) List(selector labels.Selector) (ret []*v1alpha1.SimpleExample, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SimpleExample))
	})
	return ret, err
}

// SimpleExamples returns an object that can list and get SimpleExamples.
func (s *simpleExampleLister) SimpleExamples(namespace string) SimpleExampleNamespaceLister {
	return simpleExampleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SimpleExampleNamespaceLister helps list and get SimpleExamples.
type SimpleExampleNamespaceLister interface {
	// List lists all SimpleExamples in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.SimpleExample, err error)
	// Get retrieves the SimpleExample from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.SimpleExample, error)
	SimpleExampleNamespaceListerExpansion
}

// simpleExampleNamespaceLister implements the SimpleExampleNamespaceLister
// interface.
type simpleExampleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SimpleExamples in the indexer for a given namespace.
func (s simpleExampleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.SimpleExample, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SimpleExample))
	})
	return ret, err
}

// Get retrieves the SimpleExample from the indexer for a given namespace and name.
func (s simpleExampleNamespaceLister) Get(name string) (*v1alpha1.SimpleExample, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("simpleexample"), name)
	}
	return obj.(*v1alpha1.SimpleExample), nil
}
